### ISSUE TITLE
Does not work properly with input type="radio"

### ISSUE THREAD

**Issue by pduersteler** [glaucocustodio/angular-initial-value#8]
I just tried to implement initial-value for radio buttons, which unfortunately does not work the way I understand it. My approach was the following: http://codepen.io/anon/pen/OyqXGw

The problem is that using `checked="checked"` and `initial-value` attributes together works, but only for the one radio button having them assigned, and only if it is the only radio button having it. 

This works, for the first one only:

```
<input 
  initial-value
  checked="checked"
  type="radio"
  name="foo"
  value="1"
  ng-model="name"  /> one

<input 
  type="radio"
 name="foo"
 value="2"
 ng-model="name"  /> two
```

But as e.g. the second radio button should be used as initial-value if it is checked, I thought I just continue and also add "initial-value" to the second radio:

```
<input 
  initial-value
  checked="checked"
  type="radio"
  name="foo"
  value="1"
  ng-model="name"  /> one

<input 
  initial-value
  type="radio"
 name="foo"
 value="2"
 ng-model="name"  /> two
```

This breaks the whole intial-value directive and no initial value is set for the model

**Comment by pduersteler** [comment]
Found the problem on https://github.com/glaucocustodio/angular-initial-value/blob/master/src/angular-initial-value.js#L50

On L47 you check if there is an ngModel assigned, and then on L50, you assign either `values` (for the select) or `val` for other things. This however won't work, as this assigns `undefined` for radios that should not have a value set (which is why it only works on the last radio button; there, the correct value is set. If the second should be set, the third overrides it with `undefined`).

IMHO, there shouldn't either be variables `val` and `values` as I can imagine the unclear naming being a possible source of the problem.

Replacing L47 with `if($attrs.ngModel && (val || (values != undefined && values.length))){`  solves the problem, but I deem this not as a clean solution as it smells (code repetition).

**Comment by glaucocustodio** [comment]
Sorry for delay. Why do you need to have two radio buttons (in the same group) selected?

**Comment by pduersteler** [comment]
I don't have to have two selected at the same time. I need to have the one checked which has initial-value set, but that does not work for radio buttons. As described above: If I have two radio buttons and the second one is checked, the initial-value fails.

**Comment by glaucocustodio** [comment]
I got it. Thanks for the feedback, I've put your fix for while. See https://github.com/glaucocustodio/angular-initial-value/commit/b92b4c8501781cb1db16d56843dfb52b8cf8db08.
